[package]
name = "example_iced_widget"
version = "0.1.0"
edition = "2021"

# https://github.com/rust-lang/cargo/issues/7880
[workspace]

[dependencies]
enum-map = "2.5.0"
iced = "0.9.0"
iced_native = "0.10.3"
mina = { path = "../.." }
once_cell = "1.18.0"
